print ("\tTugas 1 Praktikum Dasar Dasar Pemrograman")
print("\t"+"_"*41)
nama = input("Masukan nama anda \t\t: ")
nim = input("Masukan nama NIM \t\t: ")
kelas = input("Masukan kelas anda \t\t: ")
angkatan = input("Masukan tahun angkatan anda \t: ")
alamat = input("Masukan alamat anda \t\t: ")
print("\t"+"_"*41)
dataDiri = (f"Hallo {nama} dengan NIM {nim} dari kelas {kelas} angkatan tahun {angkatan}. Alamat anda berada di {alamat}.")
print(dataDiri)